### ISSUE TITLE
Wiko: NoClassDefFoundError: android.support.v7

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#261]
Apprently issue #248 is still not fixed.

This happend on a Wiko Rainbow model. Maybe someone can take a look agian

```
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
at android.support.v7.app.ActionBarActivityDelegateBase.initializePanelMenu(ActionBarActivityDelegateBase.java:914)
at android.support.v7.app.ActionBarActivityDelegateBase.preparePanel(ActionBarActivityDelegateBase.java:964)
at android.support.v7.app.ActionBarActivityDelegateBase.doInvalidatePanelMenu(ActionBarActivityDelegateBase.java:1182)
at android.support.v7.app.ActionBarActivityDelegateBase.access$100(ActionBarActivityDelegateBase.java:79)
at android.support.v7.app.ActionBarActivityDelegateBase$1.run(ActionBarActivityDelegateBase.java:118)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5391)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kordianbruck** [comment]
[Solution thread on SO](http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder)

**Comment by MisterY** [comment]
Do you have a confirmation that this solution worked? Would love to hear about your experience as we are having the same problem with some 4.2.2 devices, including Wiko Rainbow.

**Comment by pfent** [comment]
I think @thomasmauerer has one of the affedted devices to test this?

**Comment by thomasmauerer** [comment]
No sorry, I can't confirm that. I don't have an affected device.
