### ISSUE TITLE
CursorIndexOutOfBoundsException: Index -1 in SilenceService

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#333]
The current beta release crashes on my device
Relevant stacktrace  
```
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1
at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
at de.tum.in.tumcampus.services.SilenceService.onHandleIntent(SilenceService.java:97)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by kordianbruck** [comment]
```
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 1
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
	at de.tum.in.tumcampus.services.SilenceService.onHandleIntent(SilenceService.java:110)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

My guess is, that this happens when there is no "next" lecture.

**Comment by kordianbruck** [comment]
Btw. this lead the App to crash at every start when it tried to start the silence service. I will push a update for 1.3.0 in the next couple hours
