### ISSUE TITLE
Calendar deletion fails

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#340]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars
	at android.content.ContentResolver.delete(ContentResolver.java:954)
	at de.tum.in.tumcampus.auxiliary.calendar.CalendarHelper.deleteCalendar(CalendarHelper.java:37)
	at de.tum.in.tumcampus.models.managers.CalendarManager.deleteLocalCalendar(CalendarManager.java:163)
	at de.tum.in.tumcampus.models.managers.CalendarManager.syncCalendar(CalendarManager.java:151)
	at de.tum.in.tumcampus.activities.CalendarActivity$2.doInBackground(CalendarActivity.java:261)
	at de.tum.in.tumcampus.activities.CalendarActivity$2.doInBackground(CalendarActivity.java:258)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
	... 5 more
```

**Comment by kordianbruck** [comment]
Can someone reproduce this issue? Otherwise  I am closing it. The code looks ok to me.

**Comment by kordianbruck** [comment]
Cannot reproduce on current builds.
