### ISSUE TITLE
Opening Roomfinder from MainActivity card crashes app

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#371]
```
FATAL EXCEPTION: AsyncTask #3
Process: de.tum.in.tumcampus, PID: 5137
Theme: themes:{}
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
at de.tum.in.tumcampusapp.activities.RoomFinderDetailsActivity.onLoadInBackground(RoomFinderDetailsActivity.java:185)
at de.tum.in.tumcampusapp.activities.RoomFinderDetailsActivity.onLoadInBackground(RoomFinderDetailsActivity.java:33)
at de.tum.in.tumcampusapp.activities.generic.ActivityForLoadingInBackground$1.doInBackground(ActivityForLoadingInBackground.java:63)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
at java.lang.Thread.run(Thread.java:818) 
```

**Comment by kordianbruck** [comment]
The roomfinderdetailsactivity does not currently handle this intent correctly at all. There is no code to handle the location being passed instead of the room information. :tada:
