### ISSUE TITLE
RoomFinderDetailsActivity - exception thrown when saveInstaceState

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#377]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
at de.tum.in.tumcampus.activities.RoomFinderDetailsActivity.onLoadFinished(RoomFinderDetailsActivity.java:251)
at de.tum.in.tumcampus.activities.RoomFinderDetailsActivity.onLoadFinished(RoomFinderDetailsActivity.java:36)
at de.tum.in.tumcampus.activities.generic.ActivityForLoadingInBackground$1.onPostExecute(ActivityForLoadingInBackground.java:69)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.access$500(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by kordianbruck** [comment]
I really have no clue about this exception. The lines in question do not really explain why the exception gets thrown.

**Comment by kordianbruck** [comment]
No follow up. Seems to be resolved.
