### ISSUE TITLE
ChatRoomManager: 401 Room already exists

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#379]
```
16S:Compilerbau I (IN2227)
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
16S:Einsatz und Realisierung von Datenbanksystemen (IN2031)
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
16S:Industrielle Softwareentwicklung für Ingenieure
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
16S:Industrielle Softwareentwicklung für Ingenieure - Zentralübung
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
16S:Parallele Programmierung (IN2147)
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
16S:Tutorübungen zu Einsatz und Realisierung von Datenbanksystemen (IN2031)
401 Unauthorized Room already exists
retrofit.RetrofitError: 401 Unauthorized
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at java.lang.reflect.Proxy.invoke(Proxy.java:393)
    at de.tum.in.tumcampusapp.models.$Proxy0.createRoom(Unknown Source)
    at de.tum.in.tumcampusapp.models.TUMCabeClient.createRoom(TUMCabeClient.java:132)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:169)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:135)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:136)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:33)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by kordianbruck** [comment]
This is happening because of not activated PublicKeys and in turn the verification of the check, if your request is valid. Additionally the server was not sending out activation emails in the past couple days.

I've fixed the bug on the server, but people will need to rerun the wizard to generate the email and activate their PK. We should really optimize this procedure to verify the token from TUMO on the server side instead and not require a second activation.
