### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#387]
This bug needs immediate attention!

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6566)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:911)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.requestLayout(View.java:18733)
at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
at android.view.View.requestLayout(View.java:18733)
at android.view.View.setFlags(View.java:10595)
at android.view.View.setVisibility(View.java:7431)
at de.tum.in.tumcampusapp.activities.StartupActivity.init(StartupActivity.java:111)
at de.tum.in.tumcampusapp.activities.StartupActivity.access$000(StartupActivity.java:52)
at de.tum.in.tumcampusapp.activities.StartupActivity$1.run(StartupActivity.java:137)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by kordianbruck** [comment]
So much for immediate. Why didn't I publish the fix yet - WTF?

**Comment by kordianbruck** [comment]
Seems to be resolved.
