### ISSUE TITLE
NullPointerException after upgrading the app

### ISSUE THREAD

**Issue by pfent** [TCA-Team/TumCampusApp#406]
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
   at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.replaceIntoRooms(ChatRoomManager.java:125)
   at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:124)
   at de.tum.in.tumcampusapp.activities.wizard.WizNavExtrasActivity.onLoadInBackground(WizNavExtrasActivity.java:30)
   at de.tum.in.tumcampusapp.activities.generic.ActivityForLoadingInBackground$1.doInBackground(ActivityForLoadingInBackground.java:64)
   at android.os.AsyncTask$2.call(AsyncTask.java:304)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

Any idea, why TUMCabeClient.getMemberRooms() returns null?

**Comment by pfent** [comment]
aww, just saw an error, that corresponds to the exception:
```
E/TUMCabeClient$1: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 2 path $
```

**Comment by pfent** [comment]
ah. I got an error. @kordianbruck any idea, why the key is unauthorized?
```
[text={"error":"Verfication Failed!"}]
Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://tumcabe.in.tum.de/Api/chat/members/36/rooms/}
```

**Comment by kordianbruck** [comment]
The key gets now registered via tumo online during setup. If the verification fails, you should not be able to complete the final setup step.

I haven't been able to debug this, but sometimes it fails. Its weird. We had an issue with encoding some chars when submitting the public key to the tumo server.

**Comment by pfent** [comment]
Bummer. The logcat said something along the lines of: "Successfully uploaded the key"
Probably shouldn't crash the app though…

**Comment by kordianbruck** [comment]
That doesn't mean I implemented the check correctly.

Also: Currently you can't complete the wizard without a token

**Comment by kordianbruck** [comment]
Should be fixed with the pushed code from today.

**Comment by pfent** [comment]
now I got a different NPE :tada: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int de.tum.in.tumcampusapp.models.ChatRoom.getId()' on a null object reference
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.join(ChatRoomManager.java:156)
    at de.tum.in.tumcampusapp.models.managers.ChatRoomManager.onRequestCard(ChatRoomManager.java:188)
    at de.tum.in.tumcampusapp.models.managers.CardManager.update(CardManager.java:126)
    at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:140)
    at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:36)
    at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:179)
    at java.lang.Thread.run(Thread.java:761)
```

**Comment by kordianbruck** [comment]
Can't really say, why this is happening, but that should also be fixed.
