### ISSUE TITLE
TUM Campus App (Android) crashes instantly on start and shortly after that

### ISSUE THREAD

**Issue by Gambleon** [TCA-Team/TumCampusApp#425]
* Instant Crash was caused by some service in the package de.tum.in.tumcampusapp.services

* Delayed Crash was caused repeately at de.tum.in.tumcampusapp.managers.SurveyManager.java:308 (downloadFacultiesFromExternal)

**Comment by Gambleon** [comment]
The app has btw. every permission asked for and these havent changed.
OS: CM 13.0 (12 Nov 2016)

**Comment by kordianbruck** [comment]
@Gambleon thanks for the report.

The cache I implemented (APCu with PHP 7) is segfaulting at times with the following message: 
```
[21-Nov-2016 07:00:16 Europe/Berlin] PHP Notice:  apcu_fetch(): Error at offset 832 of 964 bytes in ...
```

I'm not sure, if the guys at will be fixing these issues any time soon, as the repo looks kinda quiet (https://github.com/krakjoe/apcu). I can't really debug the issue either, as running strace on the server is just not feasible. I will probably have to rewrite the caching to use something more sophisticated like memcached, cause APC got remove and APCu really isn't where it needs to be.

**Comment by kordianbruck** [comment]
Relating stack trace would probably be the following

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.tum.in.tumcampusapp.models.tumcabe.TUMCabeStatus.getStatus()' on a null object reference
at de.tum.in.tumcampusapp.services.GcmIdentificationService$3.onResponse(GcmIdentificationService.java:181)
at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kordianbruck** [comment]
Stack trace for the delayed crash probably this one:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at de.tum.in.tumcampusapp.managers.SurveyManager.downloadFacultiesFromExternal(SurveyManager.java:308)
at de.tum.in.tumcampusapp.services.DownloadService.downloadFacultiesAndSurveyData(DownloadService.java:251)
at de.tum.in.tumcampusapp.services.DownloadService.downloadAll(DownloadService.java:210)
at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:97)
at de.tum.in.tumcampusapp.services.DownloadService.access$000(DownloadService.java:35)
at de.tum.in.tumcampusapp.services.DownloadService$1.run(DownloadService.java:175)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by Gambleon** [comment]
Seems correct to me
