### ISSUE TITLE
NPE in Calender fragment

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#426]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.runOnUiThread(java.lang.Runnable)' on a null object reference
at de.tum.in.tumcampusapp.fragments.WeekViewFragment$1.run(WeekViewFragment.java:85)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by kordianbruck** [comment]
Yea, seems resolved.
