### ISSUE TITLE
SilenceService still buggy

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#504]
```
java.lang.SecurityException: Not allowed to change Do Not Disturb state
at android.os.Parcel.readException(Parcel.java:1693)
at android.os.Parcel.readException(Parcel.java:1646)
at android.media.IAudioService$Stub$Proxy.setRingerModeExternal(IAudioService.java:1264)
at android.media.AudioManager.setRingerMode(AudioManager.java:1352)
at de.tum.in.tumcampusapp.services.SilenceService.onHandleIntent(SilenceService.java:93)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by kordianbruck** [comment]
Probably the reason why the app crashes often in the background

**Comment by pfent** [comment]
Maybe related to this?
https://stackoverflow.com/questions/39151453/in-android-7-api-level-24-my-app-is-not-allowed-to-mute-phone-set-ringer-mode

**Comment by kordianbruck** [comment]
Closed in https://github.com/TCA-Team/TumCampusApp/pull/520
