### ISSUE TITLE
MVVWidget makes app crash

### ISSUE THREAD

**Issue by jacqueline8711** [TCA-Team/TumCampusApp#518]
## Steps to Reproduce
1. put the MVVWidget somewhere on your screen
2. make sure the TUM Campus App is not running
3. Tap the reload button on the widget or the settings button and then a station

[MVVWidget_crash.txt](https://github.com/TCA-Team/TumCampusApp/files/1388292/MVVWidget_crash.txt)

**Comment by kordianbruck** [comment]
```
10-16 18:30:31.505 28257-28257/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
Process: de.tum.in.tumcampus, PID: 28257
java.lang.NullPointerException: Attempt to invoke virtual method 'de.tum.in.tumcampusapp.models.efa.WidgetDepartures de.tum.in.tumcampusapp.managers.TransportManager.getWidget(int)' on a null object reference
at de.tum.in.tumcampusapp.widgets.MVVWidget.setAlarm(MVVWidget.java:77)
at de.tum.in.tumcampusapp.widgets.MVVWidgetConfigureActivity.saveAndReturn(MVVWidgetConfigureActivity.java:191)
at de.tum.in.tumcampusapp.widgets.MVVWidgetConfigureActivity.onItemClick(MVVWidgetConfigureActivity.java:97)
at android.widget.AdapterView.performItemClick(AdapterView.java:318)
at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
at android.widget.AbsListView$3.run(AbsListView.java:4049)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
