### ISSUE TITLE
Fresh install causes room exception

### ISSUE THREAD

**Issue by anselm92** [TCA-Team/TumCampusApp#633]
## Steps to Reproduce

1. Uninstall app
2. Install it again

## Expected Result

App opens 

## Actual Result

App crashes, because of a room db illegal state exception

## Problem

```
01-22 00:47:22.297 7457-7457/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: de.tum.in.tumcampus, PID: 7457
                                                                   java.lang.RuntimeException: Unable to start receiver de.tum.in.tumcampusapp.widgets.MensaWidget: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3369)
                                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:180)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6950)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
                                                                    Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
                                                                       at android.arch.persistence.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:119)
                                                                       at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:100)
                                                                       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:133)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:310)
                                                                       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
                                                                       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
                                                                       at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
                                                                       at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
                                                                       at de.tum.in.tumcampusapp.database.dao.CafeteriaDao_Impl.getMensaNameFromId(CafeteriaDao_Impl.java:177)
                                                                       at de.tum.in.tumcampusapp.managers.CafeteriaManager.getBestMatchMensaName(CafeteriaManager.java:185)
                                                                       at de.tum.in.tumcampusapp.widgets.MensaWidget.onUpdate(MensaWidget.java:36)
                                                                       at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:95)
                                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3355)
                                                                       at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                       at android.os.Looper.loop(Looper.java:180) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6950) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835) 
```

## Suggested Enhancement :sparkles:

idk right now, we need to investigate 

### Environment
* Phone: 
* OS version: 
* TUM Campus App version: 084a6a9f
* Language:

**Comment by anselm92** [comment]
You can work around this issue by clearing app data after first start and start it again

**Comment by psukys** [comment]
This probably has relation to https://github.com/TCA-Team/TumCampusApp/issues/560#issuecomment-348933857 as we need a consistent way of handling the database (migration schemas, etc.) as currently this is handled by clearing (somewhere) previous db. I don't fully remember, but in TcaDb it is possible to resolve this by adding something like DeleteOnMigrationConflict (or something similar that intelisense offers).

**Comment by kordianbruck** [comment]
`DeleteOnMigrationConflict` is/should be activated but needs a version number bump to drop old data. When anselm reinstalled, it restored backed up app data which had a old schema.

**Comment by kordianbruck** [comment]
I've just activated destructive migrations on the master branch, but this is really part of #560 

Please come up with migrations

**Comment by psukys** [comment]
I think, it would be great to check this within continuous integration whether PR changes something database related (thus triggering Room's exception) and requiring the person to create a migration from last master to proposed PR's version. Would definitely need to check Room's documentation on this.
