### ISSUE TITLE
IO Exceptions when download pics

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#652]
So testing the latest master, there are a couple bugs that where introduced.

a lot of io exceptions happen, when the app tries to download images. If those pictures are not available, please don't log the message.

```
02-13 01:07:46.672 7143-7225/de.tum.in.tumcampus E/NetUtils: java.io.IOException 
                                                             java.io.IOException
                                                                 at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadToFile(NetUtils.java:165)
                                                                 at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadImage(NetUtils.java:199)
                                                                 at de.tum.in.tumcampusapp.managers.CacheManager.fillCache(CacheManager.java:138)
                                                                 at de.tum.in.tumcampusapp.services.FillCacheService.lambda$onHandleWork$0$FillCacheService(FillCacheService.java:39)
                                                                 at de.tum.in.tumcampusapp.services.FillCacheService$$Lambda$0.run(Unknown Source)
                                                                 at java.lang.Thread.run(Thread.java:761)
```

**Comment by anselm92** [comment]
That bug exists for quite a while now (even before introducing room)

**Comment by kordianbruck** [comment]
@anselm92 did you ever investigate this further?

**Comment by psukys** [comment]
@kordianbruck I cannot verify at the moment, but I think [this is](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/managers/CacheManager.java#L137) the reason, because Kino model changed to having empty string as default. I can check this late tonight or tomorrow

**Comment by kordianbruck** [comment]
@psukys ah, great! thanks for spotting this. I've fixed it.
