### ISSUE TITLE
Exception when sending text in chat

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#653]
So testing the latest master, there are a couple bugs that where introduced.

```
02-13 01:11:48.615 7143-7143/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: de.tum.in.tumcampus, PID: 7143
                                                                   java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                       at java.util.ArrayList.get(ArrayList.java:411)
                                                                       at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
                                                                       at android.widget.AbsListView.setItemViewLayoutParams(AbsListView.java:2430)
                                                                       at android.widget.AbsListView.obtainView(AbsListView.java:2399)
                                                                       at android.widget.ListView.makeAndAddView(ListView.java:1970)
                                                                       at android.widget.ListView.fillUp(ListView.java:738)
                                                                       at android.widget.ListView.layoutChildren(ListView.java:1711)
                                                                       at android.widget.AbsListView.onLayout(AbsListView.java:2170)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
                                                                       at android.view.View.layout(View.java:17641)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by kordianbruck** [comment]
@OliHalu this is really higher prio than the other issues :1st_place_medal:

**Comment by OliHalu** [comment]
@kordianbruck does this happen every time you send a message? I don't know why but I get no Exceptions when sending a message.

**Comment by kordianbruck** [comment]
@OliHalu  yes :man_shrugging:

**Comment by OliHalu** [comment]
@kordianbruck Hm ...sending messages works fine for me. @psukys @anselm92  Did anyone of you encounter the same bug as Kordian ?

**Comment by psukys** [comment]
Happens to me too, so far what I found out was that this happens between sending the message and receiving the intent

**Comment by kordianbruck** [comment]
@psukys I think I fixed it with the latest commit. Can you build the branch and verify?

**Comment by kordianbruck** [comment]
Fixed in PR
