### ISSUE TITLE
Wizard - Some weird exception

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#685]
```
org.simpleframework.xml.core.ElementException: Element 'message' does not have a match in class de.tum.in.tumcampusapp.models.tumo.TokenConfirmation at line 3 TUMonline request failed
 org.simpleframework.xml.core.ElementException: Element 'message' does not have a match in class de.tum.in.tumcampusapp.models.tumo.TokenConfirmation at line 3
     at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
     at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
     at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
     at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
     at org.simpleframework.xml.core.Composite.read(Composite.java:201)
     at org.simpleframework.xml.core.Composite.read(Composite.java:148)
     at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
     at org.simpleframework.xml.core.Persister.read(Persister.java:625)
     at org.simpleframework.xml.core.Persister.read(Persister.java:606)
     at org.simpleframework.xml.core.Persister.read(Persister.java:584)
     at org.simpleframework.xml.core.Persister.read(Persister.java:562)
     at org.simpleframework.xml.core.Persister.read(Persister.java:499)
     at org.simpleframework.xml.core.Persister.read(Persister.java:408)
     at de.tum.in.tumcampusapp.tumonline.TUMOnlineRequest.fetch(TUMOnlineRequest.java:171)
     at de.tum.in.tumcampusapp.auxiliary.AuthenticationManager$2.run(AuthenticationManager.java:226)
```

**Comment by pfent** [comment]
Hm, this probably happens due to a TUMonline returning an Error.
Since we already catch all exceptions in `TUMOnlineRequest`, that shouldn't be a problem... I guess we can disable the logging for that?
