### ISSUE TITLE
NPE in ChatMessageCard

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#700]
```
java.lang.NullPointerException: 
  at de.tum.in.tumcampusapp.cards.ChatMessagesCard.updateViewHolder (ChatMessagesCard.java:76)
  at de.tum.in.tumcampusapp.adapters.CardsAdapter.onBindViewHolder (CardsAdapter.java:68)
  at de.tum.in.tumcampusapp.adapters.CardsAdapter.onBindViewHolder (CardsAdapter.java:25)
  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder (RecyclerView.java:6508)
  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder (RecyclerView.java:6541)
  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline (RecyclerView.java:5484)
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:5750)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5589)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5585)
  at android.support.v7.widget.LinearLayoutManager$LayoutState.next (LinearLayoutManager.java:2231)
  at android.support.v7.widget.LinearLayoutManager.layoutChunk (LinearLayoutManager.java:1558)
  at android.support.v7.widget.LinearLayoutManager.fill (LinearLayoutManager.java:1518)
  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:610)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3719)
  at android.support.v7.widget.RecyclerView.dispatchLayout (RecyclerView.java:3436)
  at android.support.v7.widget.RecyclerView.onLayout (RecyclerView.java:3988)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.support.v4.widget.SwipeRefreshLayout.onLayout (SwipeRefreshLayout.java:611)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild (HeaderScrollingViewBehavior.java:132)
  at android.support.design.widget.ViewOffsetBehavior.onLayoutChild (ViewOffsetBehavior.java:42)
  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild (AppBarLayout.java:1361)
  at android.support.design.widget.CoordinatorLayout.onLayout (CoordinatorLayout.java:874)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.support.v4.widget.DrawerLayout.onLayout (DrawerLayout.java:1172)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:344)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:281)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1742)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1585)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1494)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:344)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:281)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1742)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1585)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1494)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:344)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:281)
  at com.android.internal.policy.PhoneWindow$DecorView.onLayout (PhoneWindow.java:3193)
  at android.view.View.layout (View.java:17938)
  at android.view.ViewGroup.layout (ViewGroup.java:5812)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:2666)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2367)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1437)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7397)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:920)
  at android.view.Choreographer.doCallbacks (Choreographer.java:695)
  at android.view.Choreographer.doFrame (Choreographer.java:631)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:906)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7225)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

**Comment by kordianbruck** [comment]
Maybe this helps:
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at de.tum.in.tumcampusapp.cards.ChatMessagesCard.updateViewHolder(ChatMessagesCard.java:76)
at de.tum.in.tumcampusapp.adapters.CardsAdapter.onBindViewHolder(CardsAdapter.java:68)
at de.tum.in.tumcampusapp.adapters.CardsAdapter.onBindViewHolder(CardsAdapter.java:25)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
```

**Comment by pfent** [comment]
this was probably introduced with #686, which left `mUnread` uninitialized
