### ISSUE TITLE
Migrations still seem not to work

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#701]
```
java.lang.IllegalStateException: Migration didn't properly handle Kino(de.tum.in.tumcampusapp.models.tumcabe.Kino).
Expected:
TableInfo{name='Kino', columns={rating=Column{name='rating', type='TEXT', notNull=true, primaryKeyPosition=0}, link=Column{name='link', type='TEXT', notNull=true, primaryKeyPosition=0}, trailer=Column{name='trailer', type='TEXT', notNull=false, primaryKeyPosition=0}, date=Column{name='date', type='TEXT', notNull=true, primaryKeyPosition=0}, actors=Column{name='actors', type='TEXT', notNull=true, primaryKeyPosition=0}, year=Column{name='year', type='TEXT', notNull=true, primaryKeyPosition=0}, cover=Column{name='cover', type='TEXT', notNull=true, primaryKeyPosition=0}, runtime=Column{name='runtime', type='TEXT', notNull=true, primaryKeyPosition=0}, genre=Column{name='genre', type='TEXT', notNull=true, primaryKeyPosition=0}, title=Column{name='title', type='TEXT', notNull=true, primaryKeyPosition=0}, description=Column{name='description', type='TEXT', notNull=true, primaryKeyPosition=0}, id=Column{name='id', type='TEXT', notNull=true, primaryKeyPosition=1}, director=Column{name='director', type='TEXT', notNull=true, primaryKeyPosition=0}, created=Column{name='created', type='TEXT', notNull=true, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
Found:
TableInfo{name='Kino', columns={rating=Column{name='rating', type='VARCHAR', notNull=false, primaryKeyPosition=0}, link=Column{name='link', type='TEXT', notNull=false, primaryKeyPosition=0}, trailer=Column{name='trailer', type='TEXT', notNull=false, primaryKeyPosition=0}, date=Column{name='date', type='VARCHAR', notNull=false, primaryKeyPosition=0}, actors=Column{name='actors', type='TEXT', notNull=false, primaryKeyPosition=0}, year=Column{name='year', type='VARCHAR', notNull=false, primaryKeyPosition=0}, cover=Column{name='cover', type='TEXT', notNull=false, primaryKeyPosition=0}, runtime=Column{name='runtime', type='VARCHAR', notNull=false, primaryKeyPosition=0}, genre=Column{name='genre', type='VARCHAR', notNull=false, primaryKeyPosition=0}, title=Column{name='title', type='TEXT', notNull=false, primaryKeyPosition=0}, description=Column{name='description', type='TEXT', notNull=false, primaryKeyPosition=0}, id=Column{name='id', type='INTEGER', notNull=false, primaryKeyPosition=1}, director=Column{name='director', type='TEXT', notNull=false, primaryKeyPosition=0}, created=Column{name='created', type='VARCHAR', notNull=false, primaryKeyPosition=0}}, foreignKeys=[], indices=[]}
at de.tum.in.tumcampusapp.database.TcaDb_Impl$1.validateMigration(TcaDb_Impl.java:309)
at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:75)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:118)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
at android.arch.persistence.room.RoomDatabase.compileStatement(RoomDatabase.java:204)
at android.arch.persistence.room.SharedSQLiteStatement.createNewStatement(SharedSQLiteStatement.java:65)
at android.arch.persistence.room.SharedSQLiteStatement.getStmt(SharedSQLiteStatement.java:72)
at android.arch.persistence.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.java:87)
at de.tum.in.tumcampusapp.database.dao.CafeteriaDao_Impl.removeCache(CafeteriaDao_Impl.java:76)
at de.tum.in.tumcampusapp.database.TcaDb.resetDb(TcaDb.java:186)
at de.tum.in.tumcampusapp.activities.StartupActivity.setupNewVersion(StartupActivity.java:308)
at de.tum.in.tumcampusapp.activities.StartupActivity.init(StartupActivity.java:99)
at de.tum.in.tumcampusapp.activities.StartupActivity.bridge$lambda$0$StartupActivity(StartupActivity.java)
at de.tum.in.tumcampusapp.activities.StartupActivity$$Lambda$2.run(Unknown Source)
at java.lang.Thread.run(Thread.java:760)
```

I'm really not sure, why room is such a headache

**Comment by kordianbruck** [comment]
https://stackoverflow.com/questions/45664478/using-an-existing-varchar-column-with-room

**Comment by pfent** [comment]
@kordianbruck I would suggest just dropping and recreating the table, since the movies should get downloaded regularely anyways?

**Comment by kordianbruck** [comment]
@pfent yea, thats exactly what we did: https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/database/migrations/Migration2to3.kt#L15

Do new databases not go through the migrations? I'm not clear how it would be possible to get an inconsistent state.

**Comment by pfent** [comment]
I see a `SELECT * FROM kino` [here](https://github.com/TCA-Team/TumCampusApp/blob/master/app/src/main/java/de/tum/in/tumcampusapp/database/migrations/Migration2to3.kt#L25)

Since there is still a varchar column in the *old* table, that crashes Room...

Something like this should be sufficient, without copying any data:
```SQL
DROP TABLE IF EXISTS  kino;
CREATE TABLE kino (id, title, ...);
```

**Comment by kordianbruck** [comment]
@pfent are you saying the migration throws an exception and does not complete? Really?

**Comment by pfent** [comment]
I think so, that almost literally what the exception says :smiley_cat: 
> Migration didn't properly handle Kino

**Comment by kordianbruck** [comment]
@pfent that would stop the migration pre-verification and not complete it. I had it happen to me before. I'm certain that the migration works, but for whatever reason it does not get executed.

**Comment by kordianbruck** [comment]
My suspicion is, that a fresh Installation of the app, does not use migrations to create the DB, but rather creates it from the models for that version 3.

@anselm92 could you please also activate versioning for the db while you are at it.

**Comment by anselm92** [comment]
So i tried different things now (In each case cleared cache, data and uninstalled)

Installed 1.5.1 -> updated to latest using gplay
Installed 1.5.2 -> updated to latest using gplay
Installed 1.5.3

In none of the above cases any exception related to room has been thrown, am i missing anything? I'm not able to reproduce the exception

**Comment by kordianbruck** [comment]
Did you setup a token before upgrading? Did you try 1.5.1 to 1.5.2 to 1.5.3?

**Comment by anselm92** [comment]
Thanks, that caused it

**Comment by kordianbruck** [comment]
Upgrade seems to work now. Tested it with the latest Beta Release.
