### ISSUE TITLE
NetUtils - downloading invalid URLs still crashes the app

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/TumCampusApp#703]
```
java.lang.IllegalArgumentException: unexpected url: 
at okhttp3.Request$Builder.url(Request.java:143)
at de.tum.in.tumcampusapp.auxiliary.NetUtils.getOkHttpResponse(NetUtils.java:95)
at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadToFile(NetUtils.java:161)
at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadImage(NetUtils.java:198)
at de.tum.in.tumcampusapp.managers.CacheManager.fillCache(CacheManager.java:135)
at de.tum.in.tumcampusapp.services.FillCacheService.lambda$onHandleWork$0$FillCacheService(FillCacheService.java:39)
at de.tum.in.tumcampusapp.services.FillCacheService$$Lambda$0.run(Unknown Source)
at java.lang.Thread.run(Thread.java:762)
```

this shouldn't happen

**Comment by pfent** [comment]
the crash was already fixed in 188f05360ca87a3bf7ea50e3726705868e9a3978

`IllegalArgumentException` is catched in `downloadImage()`, are you still on an old version?

**Comment by kordianbruck** [comment]
No, this is on 1.5.3

**Comment by pfent** [comment]
then you kindly explain to me, how a IllegalArgumentexception can escape a
```java
try {
...
} catch (IllegalArgumentException e) {
}
```

**Comment by kordianbruck** [comment]
@pfent are you sure its the correct function? Don't we have like several overloaded functions in that same class with the same name?

**Comment by pfent** [comment]
looking at the stacktrace:
> at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadImage(NetUtils.java:198)

looking at the source:
`downloadImage()` is not overloaded
in `downloadImage()` line 203ff, the Exception is catched, but logged

Are you sure this is the cause for the app crash, because that stacktrace is probably only a logmessage

**Comment by kordianbruck** [comment]
Dunno really, maybe it was something wrong with the bugreport view - I can't reproduce this with the latest 1.5 branch.
