### ISSUE TITLE
App crashes on Android 4.4.2 when Internet connection is available

### ISSUE THREAD

**Issue by M-FF-M** [TCA-Team/TumCampusApp#714]
## Steps to Reproduce

1. Start app on an Android 4.4.2 phone with Wifi or mobile network switched on

## Expected Result
App opens and first displays the loading screen, then the home screen (or whatever you call it).

## Actual Result
The loading screen is displayed and then I get the message 'Unfortunately, TUM Campus App has stopped'  - the home screen is never displayed.

## Problem
This issue only appeared after updating to the newest version (and persisted after uninstalling and reinstalling the app).

Android studio debugger output:
```
02-23 12:35:54.278 2905-3550/? E/NetUtils: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                           javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410)
                                               at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
                                               at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
                                               at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
                                               at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
                                               at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
                                               at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
                                               at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                               at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                               at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                               at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                               at de.tum.in.tumcampusapp.api.Helper.lambda$getDeviceInterceptor$1$Helper(Helper.java:106)
                                               at de.tum.in.tumcampusapp.api.Helper$$Lambda$1.intercept(Unknown Source)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                               at okhttp3.RealCall.execute(RealCall.java:77)
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.getOkHttpResponse(NetUtils.java:100)
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadStringHttp(NetUtils.java:113)
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:276)
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:45)
                                               at de.tum.in.tumcampusapp.managers.CafeteriaMenuManager.downloadFromExternal(CafeteriaMenuManager.java:94)
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadCafeterias(DownloadService.java:237)
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadAll(DownloadService.java:228)
                                               at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:116)
                                               at de.tum.in.tumcampusapp.services.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:198)
                                               at de.tum.in.tumcampusapp.services.DownloadService$$Lambda$0.run(Unknown Source)
                                               at java.lang.Thread.run(Thread.java:864)
                                            Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                               at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
                                               at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202)
                                               at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612)
                                               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
                                               at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299) 
                                               at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268) 
                                               at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) 
                                               at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) 
                                               at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) 
                                               at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) 
                                               at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at de.tum.in.tumcampusapp.api.Helper.lambda$getDeviceInterceptor$1$Helper(Helper.java:106) 
                                               at de.tum.in.tumcampusapp.api.Helper$$Lambda$1.intercept(Unknown Source) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                                               at okhttp3.RealCall.execute(RealCall.java:77) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.getOkHttpResponse(NetUtils.java:100) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadStringHttp(NetUtils.java:113) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:276) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:45) 
                                               at de.tum.in.tumcampusapp.managers.CafeteriaMenuManager.downloadFromExternal(CafeteriaMenuManager.java:94) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadCafeterias(DownloadService.java:237) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadAll(DownloadService.java:228) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:116) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:198) 
                                               at de.tum.in.tumcampusapp.services.DownloadService$$Lambda$0.run(Unknown Source) 
                                               at java.lang.Thread.run(Thread.java:864) 
                                            Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                               at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282) 
                                               at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:202) 
                                               at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:612) 
                                               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406) 
                                               at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299) 
                                               at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268) 
                                               at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) 
                                               at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) 
                                               at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) 
                                               at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) 
                                               at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at de.tum.in.tumcampusapp.api.Helper.lambda$getDeviceInterceptor$1$Helper(Helper.java:106) 
                                               at de.tum.in.tumcampusapp.api.Helper$$Lambda$1.intercept(Unknown Source) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                                               at okhttp3.RealCall.execute(RealCall.java:77) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.getOkHttpResponse(NetUtils.java:100) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadStringHttp(NetUtils.java:113) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:276) 
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadJson(NetUtils.java:45) 
                                               at de.tum.in.tumcampusapp.managers.CafeteriaMenuManager.downloadFromExternal(CafeteriaMenuManager.java:94) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadCafeterias(DownloadService.java:237) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.downloadAll(DownloadService.java:228) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:116) 
                                               at de.tum.in.tumcampusapp.services.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:198) 
                                               at de.tum.in.tumcampusapp.services.DownloadService$$Lambda$0.run(Unknown Source) 
                                               at java.lang.Thread.run(Thread.java:864) 
```

I also get the following error before even starting the app (when turning on Wifi):
```
02-23 12:34:46.913 2866-2893/? E/AndroidRuntime: FATAL EXCEPTION: Thread-219
                                                 Process: de.tum.in.tumcampus, PID: 2866
                                                 java.lang.NoSuchMethodError: android.net.wifi.WifiEnterpriseConfig.getAltSubjectMatch
                                                         at de.tum.in.tumcampusapp.cards.EduroamFixCard.checkDNSName(EduroamFixCard.java:180)
                                                         at de.tum.in.tumcampusapp.cards.EduroamFixCard.isConfigValid(EduroamFixCard.java:152)
                                                         at de.tum.in.tumcampusapp.cards.EduroamFixCard.shouldShow(EduroamFixCard.java:80)
                                                         at de.tum.in.tumcampusapp.cards.generic.Card.apply(Card.java:157)
                                                         at de.tum.in.tumcampusapp.cards.generic.NotificationAwareCard.apply(NotificationAwareCard.java:88)
                                                         at de.tum.in.tumcampusapp.managers.CardManager.update(CardManager.java:122)
                                                         at de.tum.in.tumcampusapp.services.DownloadService.download(DownloadService.java:145)
                                                         at de.tum.in.tumcampusapp.services.DownloadService.lambda$onHandleWork$0$DownloadService(DownloadService.java:198)
                                                         at de.tum.in.tumcampusapp.services.DownloadService$$Lambda$0.run(Unknown Source)
                                                         at java.lang.Thread.run(Thread.java:864)
```

And the following error when starting the app without Internet connection (this one is not that bad, I suppose, you can probably ignore it):
```
02-23 12:33:44.982 2686-2827/? E/NetUtils: java.io.IOException https://tumcabe.in.tum.de/File/news/sources/src_1.png
                                           java.io.IOException
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadToFile(NetUtils.java:165)
                                               at de.tum.in.tumcampusapp.auxiliary.NetUtils.downloadImage(NetUtils.java:196)
                                               at de.tum.in.tumcampusapp.managers.CacheManager.fillCache(CacheManager.java:129)
                                               at de.tum.in.tumcampusapp.services.FillCacheService.lambda$onHandleWork$0$FillCacheService(FillCacheService.java:39)
                                               at de.tum.in.tumcampusapp.services.FillCacheService$$Lambda$0.run(Unknown Source)
                                               at java.lang.Thread.run(Thread.java:864)
```
### Environment
* Phone: Alcatel One Touch Pixi First (4024X)
* OS version: Android 4.4.2
* TUM Campus App version: v1.5.3
* Language: English

**Comment by M-FF-M** [comment]
If I open the app without internet connection it works as expected - but as soon as I turn on Wifi the app crashes again.

**Comment by pfent** [comment]
The WiFi issue will be fixed in the next release with  #708, @jacqueline8711 is already on it.

**Comment by pfent** [comment]
The IOException should be only a log message, that shouldn't crash the app...

**Comment by M-FF-M** [comment]
The IOException doesn't crash the app - as I said, you can probably ignore it.

**Comment by kordianbruck** [comment]
@pfent this is not an wifi/eduroam Problem. The Problem Here is that we have the wrong certificate pinned for the domain.
We should remove the pinning for cafeterias, as those certificates might be switched out at any point in time.

**Comment by pfent** [comment]
@kordianbruck There are 3 different Exceptions :see_no_evil:  
The cafeteria endpoint is http right now: 
```
http://lu32kap.typo3.lrz.de/mensaapp/exportDB.php?mensa_id=all
```

However, I get a HTTP 308 to `www.devapp.it.tum.de/mensaapp`, for which we pin the certificate (which is totally valid IMHO)

**Comment by pfent** [comment]
Just debugged this on an 4.4 emulator:
The app doesn't crash due to the SSL Exception, but Studyrooms and Cafeterias are not available.
Furthermore, even when completely disabling the certificate pinning, I still get a `SSLHandshakeException`.

I guess the SSL configuration of the `devapp.it.tum.de` server isn't compatible with Android 4.4. This might be a relevant reason for #711

@kordianbruck do you have any insight about the SSL config of that server?

**Comment by kordianbruck** [comment]
@xsrf does maybe just a bit?

**Comment by kordianbruck** [comment]
@pfent we can proxy those requests via our Server if needed.

**Comment by anselm92** [comment]
ssllabs does not show any issues for android version 4 or below, see results:

https://www.ssllabs.com/ssltest/analyze.html?d=www.devapp.it.tum.de&s=129.187.254.228&hideResults=on

**Comment by xsrf** [comment]
The new DFN PKI is not compatible with Android 4.4 or lower because the root certificate "T-TeleSec GlobalRoot Class 2" is not supplied with these Android versions, see https://www.pki.dfn.de/faqpki/faq-generation-2/#c18745
All TUM/DFN related servers will migrate to this new PKI because the old root certificate "Deutsche Telekom Root CA 2" will expire in 2019.
However, devapp.it.tum.de uses the new certificate for at least half a year now.

**Comment by pfent** [comment]
That also means TUMonline will cease to work on Android 4.4 soon, too :scream: 
@kordianbruck I'm more and more convinced to just drop support for those devices...

**Comment by xsrf** [comment]
@pfent the current certificate of campus.tum.de expires on 13. ‎Juli ‎2018 ... So, yes, TUMonline won't be available on these android versions soon. Neither via the app or the regular browser.

**Comment by M-FF-M** [comment]
I checked again whether the app also crashes with mobile network connection (as I had done before - and it didn't) - but it does work now (it was probably just bad luck last time). So, it now works with mobile network connection, but not with Wifi. The Wifi problem seems to have been fixed already (see the referenced issue above), so I'll close this issue.

PS: I can totally understand that you want to drop support for Android 4, but please release the fix for the Wifi issue first - then, at least, I'll be left with a working version of the app :)

I also installed the certificate available at https://www.telesec.de/en/public-key-infrastructure/support/root-certificates/category/83-t-telesec-globalroot-class-2 on my phone (that should be the one you were talking about) and it looks like the Handshake Exception disappeared (I could only run a very quick test, so I'm not totally sure).
