### ISSUE TITLE
Roomfinder & LecturesPersonalActivity crashes app on Android 8

### ISSUE THREAD

**Issue by xsrf** [TCA-Team/TumCampusApp#719]
## Steps to Reproduce

1. Roomfinder
2. Search "n1190"
3. Tap first result

## Expected Result

Map of N1190

## Actual Result

App crashes (same with other rooms)
First two exceptions are thrown when you search for the room
Last exception is thrown when you click on the first result (which then crashes the app)
Also if you open the roomfinder and then minimize the app it'll throw the same exception and crash.

### Environment
* Phone: Nexus 5X
* OS version: 8.1.0
* TUM Campus App version: v1.5.3
* Language: de

```
02-25 23:29:26.837 22486-23716/de.tum.in.tumcampus E/ActivityThread: Failed to find provider info for de.tum.in.tumcampusapp.component.officialtum.roomfinder.RoomFinderSuggestionProvider
02-25 23:29:26.838 22486-23716/de.tum.in.tumcampus E/SearchSuggestions: saveRecentQuery
                                                                        java.lang.IllegalArgumentException: Unknown URL content://de.tum.in.tumcampusapp.component.officialtum.roomfinder.RoomFinderSuggestionProvider/suggestions
                                                                            at android.content.ContentResolver.insert(ContentResolver.java:1551)
                                                                            at android.provider.SearchRecentSuggestions.saveRecentQueryBlocking(SearchRecentSuggestions.java:201)
                                                                            at android.provider.SearchRecentSuggestions.-wrap0(Unknown Source:0)
                                                                            at android.provider.SearchRecentSuggestions$1.run(SearchRecentSuggestions.java:172)
02-25 23:29:26.838 22486-23716/de.tum.in.tumcampus E/ActivityThread: Failed to find provider info for de.tum.in.tumcampusapp.component.officialtum.roomfinder.RoomFinderSuggestionProvider
02-25 23:29:26.838 22486-23716/de.tum.in.tumcampus E/SearchSuggestions: truncateHistory
                                                                        java.lang.IllegalArgumentException: Unknown URL content://de.tum.in.tumcampusapp.component.officialtum.roomfinder.RoomFinderSuggestionProvider/suggestions
                                                                            at android.content.ContentResolver.delete(ContentResolver.java:1648)
                                                                            at android.provider.SearchRecentSuggestions.truncateHistory(SearchRecentSuggestions.java:243)
                                                                            at android.provider.SearchRecentSuggestions.saveRecentQueryBlocking(SearchRecentSuggestions.java:207)
                                                                            at android.provider.SearchRecentSuggestions.-wrap0(Unknown Source:0)
                                                                            at android.provider.SearchRecentSuggestions$1.run(SearchRecentSuggestions.java:172)
02-25 23:29:27.567 3292-3292/? E/NetworkController: GSM STATE_IN_SERVICE mESimEnable = false, slot 0
02-25 23:29:28.126 2986-20465/? E/ActivityTrigger: activityStartTrigger: not whiteListedde.tum.in.tumcampus/de.tum.in.tumcampusapp.component.tumui.roomfinder.RoomFinderDetailsActivity/999999
02-25 23:29:28.644 22486-22486/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: de.tum.in.tumcampus, PID: 22486
                                                                     java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
                                                                         at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
                                                                         at android.view.View.dispatchSaveInstanceState(View.java:17600)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3727)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3733)
                                                                         at android.view.View.saveHierarchyState(View.java:17583)
                                                                         at com.android.internal.policy.PhoneWindow.saveHierarchyState(PhoneWindow.java:2105)
                                                                         at android.app.Activity.onSaveInstanceState(Activity.java:1572)
                                                                         at android.support.v4.app.SupportActivity.onSaveInstanceState(SupportActivity.java:74)
                                                                         at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:538)
                                                                         at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
                                                                         at android.app.Activity.performSaveInstanceState(Activity.java:1502)
                                                                         at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1476)
                                                                         at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5057)
                                                                         at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4330)
                                                                         at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4389)
                                                                         at android.app.ActivityThread.-wrap24(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:180)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6950)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)```

**Comment by xsrf** [comment]
Cannot reproduce on Nexus 7 (2013) / 6.0.1

**Comment by kordianbruck** [comment]
Neither on Android 7.1 (Onplus5 on Linageos)

**Comment by jacqueline8711** [comment]
I can reproduce this (also Android 8.1.0)

FATAL EXCEPTION: main
                                                                     Process: de.tum.in.tumcampus, PID: 10916
                                                                     java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
                                                                         at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
                                                                         at android.view.View.dispatchSaveInstanceState(View.java:17614)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3720)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3726)
                                                                         at android.view.View.saveHierarchyState(View.java:17597)
                                                                         at com.android.internal.policy.PhoneWindow.saveHierarchyState(PhoneWindow.java:2096)
                                                                         at android.app.Activity.onSaveInstanceState(Activity.java:1566)
                                                                         at android.support.v4.app.SupportActivity.onSaveInstanceState(SupportActivity.java:74)
                                                                         at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:538)
                                                                         at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
                                                                         at android.app.Activity.performSaveInstanceState(Activity.java:1496)
                                                                         at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
                                                                         at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
                                                                         at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4025)
                                                                         at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084)
                                                                         at android.app.ActivityThread.-wrap24(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by anselm92** [comment]
I can reproduce it on Android 8.0 HTC U11 Latest master (will add stacktrace)

**Comment by psukys** [comment]
By the looks of the first stack trace, it might be the case that I didn't handle some rough edges in #677, @anselm92 is your stack trace similar to first one?

**Comment by kordianbruck** [comment]
Well #721 is not yet deployed and was fixed after 1.5.3 - so if you can reproduce on latest master, the issue is not yet resolved.

**Comment by kordianbruck** [comment]
Known bug in the Library we use: https://github.com/emilsjolander/StickyListHeaders/issues/477

**Comment by pfent** [comment]
https://github.com/emilsjolander/StickyListHeaders/issues/477#issuecomment-345310364

There's a workaround...
But we probably should look for a maintained alternative...
