### ISSUE TITLE
Crash on first open

### ISSUE THREAD

**Issue by thellmund** [TCA-Team/TumCampusApp#878]
## Steps to reproduce
1. Clear all data of the TUM Campus app
2. Open the app

## Console output
06-09 21:52:49.814 10923-11196/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: Thread-16
    Process: de.tum.in.tumcampus, PID: 10923
    android.database.sqlite.SQLiteException: index index_transport_favorites_symbol already exists (code 1 SQLITE_ERROR): , while compiling: CREATE UNIQUE INDEX `index_transport_favorites_symbol` ON `transport_favorites` (`symbol`)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:901)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:512)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1769)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
        at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:240)
        at de.tum.in.tumcampusapp.database.TcaDb_Impl$1.createAllTables(TcaDb_Impl.java:135)
        at android.arch.persistence.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:61)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:113)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
        at de.tum.in.tumcampusapp.utils.sync.SyncDao_Impl.getSyncSince(SyncDao_Impl.java:87)
        at de.tum.in.tumcampusapp.utils.sync.SyncManager.needSync(SyncManager.java:48)
        at de.tum.in.tumcampusapp.utils.sync.SyncManager.needSync(SyncManager.java:36)
        at de.tum.in.tumcampusapp.component.ui.cafeteria.controller.CafeteriaMenuManager.downloadFromExternal(CafeteriaMenuManager.java:92)
        at de.tum.in.tumcampusapp.service.DownloadService.downloadCafeterias(DownloadService.kt:108)
        at de.tum.in.tumcampusapp.service.DownloadService.downloadAll(DownloadService.kt:99)
        at de.tum.in.tumcampusapp.service.DownloadService.access$downloadAll(DownloadService.kt:37)
        at de.tum.in.tumcampusapp.service.DownloadService$Companion.download(DownloadService.kt:188)
        at de.tum.in.tumcampusapp.service.DownloadService$Companion.access$download(DownloadService.kt:147)
        at de.tum.in.tumcampusapp.service.DownloadService$onHandleWork$1.run(DownloadService.kt:72)
        at java.lang.Thread.run(Thread.java:764)

**Comment by thellmund** [comment]
Fixed this in #880.

**Comment by jacqueline8711** [comment]
@thellmund can this be closed?

**Comment by thellmund** [comment]
Can be closed.

**Comment by thellmund** [comment]
Can be closed.
